Repository moshell-lang/moshell, pull requests merged in 2023-03, with the labels that each got.

#19 Parse arithmetic, comparisons and boolean operations
  lexer/src/token.rs
  lexer/tests/sample.rs
  parser/Cargo.toml
  parser/src/aspects.rs
  parser/src/aspects/binary_operation_parser.rs
  parser/src/aspects/call_parser.rs
  parser/src/aspects/group_parser.rs
  parser/src/aspects/literal_parser.rs
  parser/src/aspects/redirection_parser.rs
  parser/src/aspects/substitution_parser.rs
  parser/src/aspects/var_declaration_parser.rs
  parser/src/ast.rs
  parser/src/ast/group.rs
  parser/src/ast/operation.rs
  parser/src/ast/statement.rs
  parser/src/ast/substitution.rs
  parser/src/lib.rs
  parser/src/moves.rs
  parser/src/parser.rs
  parser/tests/with_lexer.rs
Labels: enhancement

#22 Proposal to reduce names in /aspects folder, rename XParser traits to XAspect, and replace 'name' token fields with str
  parser/src/aspects.rs
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/call.rs
  parser/src/aspects/group.rs
  parser/src/aspects/literal.rs
  parser/src/aspects/redirection.rs
  parser/src/aspects/substitution.rs
  parser/src/aspects/var_declaration.rs
  parser/src/aspects/var_reference.rs
  parser/src/ast/variable.rs
  parser/src/parser.rs
  parser/tests/expr.rs
  parser/tests/with_lexer.rs
Labels: proposal

#24 Parse test expressions
  lexer/src/token.rs
  lexer/tests/sample.msh
  lexer/tests/sample.rs
  parser/src/aspects.rs
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/call.rs
  parser/src/aspects/group.rs
  parser/src/aspects/literal.rs
  parser/src/aspects/test.rs
  parser/src/aspects/var_reference.rs
  parser/src/ast.rs
  parser/src/ast/literal.rs
  parser/src/ast/test.rs
  parser/src/moves.rs
  parser/src/parser.rs
Labels: enhancement

#27 Make parser look for non-blank and non-eox inputs before trying to parse a statement.
  parser/src/parser.rs
  parser/tests/with_lexer.rs
Labels: bugfix

#26 Fix #23, enhanced template string lexemes, added `ParserCursor::select` and `NotMove`
  lexer/src/token.rs
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/call.rs
  parser/src/aspects/group.rs
  parser/src/aspects/literal.rs
  parser/src/aspects/redirection.rs
  parser/src/aspects/substitution.rs
  parser/src/aspects/test.rs
  parser/src/aspects/var_declaration.rs
  parser/src/aspects/var_reference.rs
  parser/src/ast/literal.rs
  parser/src/ast/substitution.rs
  parser/src/cursor.rs
  parser/src/moves.rs
  parser/tests/expr.rs
  parser/tests/with_lexer.rs
Labels: bugfix

#34 Parse if / else statements and expressions
  lexer/src/token.rs
  parser/src/aspects.rs
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/if_else.rs
  parser/src/aspects/test.rs
  parser/src/ast.rs
  parser/src/ast/control_flow.rs
  parser/src/moves.rs
  parser/src/parser.rs
Labels: enhancement

#40 Add Parser aspect for match expressions
  lexer/src/token.rs
  parser/src/aspects.rs
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/call.rs
  parser/src/aspects/group.rs
  parser/src/aspects/if_else.rs
  parser/src/aspects/literal.rs
  parser/src/aspects/match.rs
  parser/src/aspects/redirection.rs
  parser/src/aspects/substitution.rs
  parser/src/aspects/test.rs
  parser/src/aspects/use.rs
  parser/src/aspects/var_declaration.rs
  parser/src/aspects/var_reference.rs
  parser/src/ast.rs
  parser/src/ast/match.rs
  parser/src/ast/test.rs
  parser/src/ast/use.rs
  parser/src/ast/value.rs
  parser/src/moves.rs
  parser/src/parser.rs
  parser/tests/expr.rs
  parser/tests/with_lexer.rs
Labels: enhancement

#45 Add loop / while and "detached" aspects, fix % and / oversights, fix call arguments
  lexer/src/token.rs
  parser/src/aspects.rs
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/call.rs
  parser/src/aspects/detached.rs
  parser/src/aspects/if_else.rs
  parser/src/aspects/literal.rs
  parser/src/aspects/loop.rs
  parser/src/aspects/match.rs
  parser/src/aspects/redirection.rs
  parser/src/aspects/substitution.rs
  parser/src/aspects/test.rs
  parser/src/aspects/use.rs
  parser/src/aspects/var_declaration.rs
  parser/src/aspects/var_reference.rs
  parser/src/ast.rs
  parser/src/ast/callable.rs
  parser/src/ast/control_flow.rs
  parser/src/ast/match.rs
  parser/src/ast/use.rs
  parser/src/moves.rs
  parser/src/parser.rs
  parser/tests/expr.rs
  parser/tests/with_lexer.rs
Labels: enhancement, bugfix

#56 add typed parameters for calls
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/call.rs
  parser/src/aspects/detached.rs
  parser/src/aspects/group.rs
  parser/src/aspects/if_else.rs
  parser/src/aspects/loop.rs
  parser/src/aspects/match.rs
  parser/src/aspects/redirection.rs
  parser/src/aspects/substitution.rs
  parser/src/aspects/test.rs
  parser/src/aspects/var_declaration.rs
  parser/src/ast/callable.rs
  parser/tests/err.rs
  parser/tests/expr.rs
  parser/tests/with_lexer.rs
Labels: enhancement

#59 Parse for statements
  ast/src/control_flow.rs
  ast/src/lib.rs
  ast/src/range.rs
  lexer/src/token.rs
  parser/src/aspects.rs
  parser/src/aspects/literal.rs
  parser/src/aspects/loop.rs
  parser/src/aspects/range.rs
  parser/src/err.rs
  parser/src/parser.rs
  parser/tests/err.rs
  parser/tests/expr.rs
Labels: enhancement

#71 Add return keyword
  ast/src/function.rs
  ast/src/lib.rs
  parser/src/aspects/function_declaration.rs
  parser/src/parser.rs
Labels: bugfix

#69 Parse Lambda type declarations
  ast/src/lib.rs
  ast/src/type.rs
  cli/src/main.rs
  lexer/src/token.rs
  parser/src/aspects/call.rs
  parser/src/aspects/function_declaration.rs
  parser/src/aspects/group.rs
  parser/src/aspects/match.rs
  parser/src/aspects/redirection.rs
  parser/src/aspects/type.rs
  parser/src/aspects/var_declaration.rs
  parser/src/err.rs
  parser/src/parser.rs
  parser/tests/expr.rs
Labels: enhancement

#68 Parse function calls with parentheses
  ast/src/call.rs
  ast/src/lib.rs
  ast/src/structure.rs
  ast/src/type.rs
  cli/src/main.rs
  lexer/src/token.rs
  parser/src/aspects.rs
  parser/src/aspects/call.rs
  parser/src/aspects/function_declaration.rs
  parser/src/aspects/literal.rs
  parser/src/aspects/match.rs
  parser/src/aspects/redirection.rs
  parser/src/aspects/structure.rs
  parser/src/aspects/type.rs
  parser/src/cursor.rs
  parser/src/err.rs
  parser/src/parser.rs
  parser/tests/err.rs
  parser/tests/expr.rs
  sandbox/src/main.rs
Labels: enhancement
