Repository moshell-lang/moshell, pull requests merged in 2023-04, with the labels that each got.

#74 Parse lambda declarations
  ast/src/lambda.rs
  ast/src/lib.rs
  parser/src/aspects.rs
  parser/src/aspects/call.rs
  parser/src/aspects/expr_list.rs
  parser/src/aspects/lambda_def.rs
  parser/src/aspects/type.rs
  parser/src/aspects/var_declaration.rs
  parser/src/cursor.rs
  parser/src/parser.rs
  parser/tests/err.rs
  parser/tests/expr.rs
Labels: enhancement

#77 Switch to an handwritten lexer
  context/src/source.rs
  lexer/Cargo.toml
  lexer/src/keyword.rs
  lexer/src/lexer.rs
  lexer/src/lib.rs
  lexer/src/literal.rs
  lexer/src/token.rs
  lexer/tests/sample.rs
  parser/src/aspects/assign.rs
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/call.rs
  parser/src/aspects/detached.rs
  parser/src/aspects/literal.rs
  parser/src/aspects/type.rs
  parser/src/aspects/use.rs
  parser/src/aspects/var_reference.rs
  parser/src/moves.rs
  parser/src/parser.rs
Labels: enhancement, bugfix

#84 Parse `as` expressions for casts
  ast/src/lib.rs
  ast/src/type.rs
  lexer/src/keyword.rs
  lexer/src/token.rs
  parser/src/aspects/type.rs
  parser/src/parser.rs
  parser/tests/expr.rs
Labels: enhancement

#86 Enhance use expressions and add inclusion path to calls and types
  ast/src/call.rs
  ast/src/type.rs
  ast/src/use.rs
  context/src/str_find.rs
  lexer/src/keyword.rs
  lexer/src/lexer.rs
  lexer/src/token.rs
  parser/src/aspects.rs
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/call.rs
  parser/src/aspects/detached.rs
  parser/src/aspects/function_declaration.rs
  parser/src/aspects/group.rs
  parser/src/aspects/if_else.rs
  parser/src/aspects/lambda_def.rs
  parser/src/aspects/loop.rs
  parser/src/aspects/match.rs
  parser/src/aspects/modules.rs
  parser/src/aspects/redirection.rs
  parser/src/aspects/substitution.rs
  parser/src/aspects/test.rs
  parser/src/aspects/type.rs
  parser/src/aspects/use.rs
  parser/src/aspects/var_declaration.rs
  parser/src/parser.rs
  parser/tests/err.rs
  parser/tests/expr.rs
  parser/tests/with_lexer.rs
Labels: enhancement

#85 Parse method calls
  ast/src/call.rs
  ast/src/lib.rs
  parser/src/aspects/call.rs
  parser/src/aspects/expr_list.rs
  parser/src/aspects/var_reference.rs
  parser/src/moves.rs
  parser/src/parser.rs
  parser/tests/expr.rs
Labels: enhancement

#90 Introduce import engine and naming system
  analyzer/src/environment.rs
  analyzer/src/import_engine.rs
  analyzer/src/lang_types.rs
  analyzer/src/layers.rs
  analyzer/src/lib.rs
  analyzer/src/name.rs
  analyzer/src/types.rs
  analyzer/src/types/class.rs
  analyzer/src/types/context.rs
  analyzer/src/types/types.rs
  context/macros/src/lib.rs
  context/src/str_find.rs
Labels: analyzer

#92 Support local parser errors
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/main.rs
  cli/src/repl.rs
  cli/src/report.rs
  lexer/src/token.rs
  parser/src/aspects/binary_operation.rs
  parser/src/aspects/call.rs
  parser/src/aspects/expr_list.rs
  parser/src/aspects/function_declaration.rs
  parser/src/aspects/group.rs
  parser/src/aspects/literal.rs
  parser/src/aspects/match.rs
  parser/src/aspects/modules.rs
  parser/src/aspects/type.rs
  parser/src/aspects/var_declaration.rs
  parser/src/aspects/var_reference.rs
  parser/src/moves.rs
  parser/src/parser.rs
  parser/tests/err.rs
  parser/tests/expr.rs
Labels: enhancement, bugfix, parser
